src/setup.py, src/synthetix/constants.py, src/synthetix/contracts/deployments/420/MulticallModule.json, src/synthetix/contracts/deployments/84531/AccountProxy.json, src/synthetix/contracts/deployments/84531/ERC7412.json, src/synthetix/contracts/deployments/84531/Multicall.json, src/synthetix/contracts/deployments/84531/PerpsMarketProxy.json, src/synthetix/contracts/deployments/84531/SpotMarketProxy.json, src/synthetix/contracts/deployments/84531/USDProxy.json, src/synthetix/perps/constants.py, src/synthetix/perps/perps.py, src/synthetix/pyth/pyth.py, src/synthetix/spot/spot.py, src/synthetix/synthetix.py, src/synthetix/utils/multicall.py, src/tests/conftest.py, src/tests/test_susd.py
Add support for ERC-7412 calls, where oracle data is fetched offchain and added to a multicall. Adds new functions to the `multicall` utils module:
* `call_erc7412` - make a single call, fetching any required offchain data
* `multicall_erc7412` - make a list of calls, fetching any required offchain data
* `write_erc7412` - Build a multicall transaction which updates oracles and submits a trade. This is currently untested.
=> Add ERC-7412 Support

docs/source/guides/trade_perps.md, docs/source/index.rst, src/synthetix/perps/perps.py
Add a perps trading guide to the docs
=> Perps trading guide

src/synthetix/perps/perps.py
* Adjust the `value` parameter when prepending oracle calls to avoid reverts
* Use multicall to fetch collateral balances
=> adjusting functions to support data returned by hermes pyth endpoints

src/synthetix/contracts/contracts.py, src/synthetix/contracts/deployments/1/CannonRegistry.json, src/synthetix/synthetix.py
Add functionality to specify a cannon deployment and fetch the contract addresses and ABIs. Since not all contracts may be in the specified deployment, the config acts as an override for the hard-coded contracts.
Usage:
```
snx = Synthetix(
provider_rpc=os.getenv('BASE_TESTNET_RPC'), # A Base Goerli RPC endpoint
network_id=84531, # Base Goerli
cannon_config = {
'package': 'synthetix-omnibus',
'version': '3.3.3-dev.e141cd8c',
'preset': 'andromeda'
}
)
```
=> Add cannon contract loading

src/synthetix/utils/multicall.py
Fixing a bug in the ERC7412 utilities where the new call is appended twice.
=> Bug: FIx duplicated pyth data

src/synthetix/core/core.py, src/synthetix/perps/perps.py
Refetch account ids after creating a new perps or core account, and set the default. This will allow a more seamless interaction:
New:
```python
create_tx = snx.perps.create_account(submit=True)
snx.wait(create_tx)
```
Old:
```python
create_tx = snx.perps.create_account(submit=True)
snx.wait(create_tx)
snx.perps.get_account_ids()
```
=> Add account ID refetch

src/synthetix/utils/multicall.py
Fix a bug where `require_success` is set to `False` on multicalls, skipping the ERC7412 data fetching.
=> Bug: multicall `require_success`

src/synthetix/synthetix.py
Some RPCs (like public ones) don't support the call for accounts. Place this call in a try/except to keep the logic, but avoid these errors.
Additionally, improve the logging around connected accounts.
=> Fix RPC signer

docs/source/guides/advanced_perps.md, src/synthetix/perps/perps.py, src/tests/test_perps_v3.py
Add the following to market info:
- maker/taker fees
- skew scale
- max funding velocity
- max market value ($)
Also, update the perps `get_quote` function to include:
- Order fees
- Settlement reward cost
=> Add market info

src/synthetix/contracts/contracts.py, src/synthetix/contracts/deployments/10/CannonRegistry.json, src/synthetix/contracts/deployments/42161/ARB.json, src/synthetix/contracts/deployments/42161/Pyth.json, src/synthetix/contracts/deployments/42161/USDC.json, src/synthetix/contracts/deployments/42161/WETH.json, src/synthetix/contracts/deployments/84532/ERC4626.json, src/synthetix/spot/spot.py, src/synthetix/synthetix.py, src/tests/e2e/arbitrum-mainnet-fork/conftest.py, src/tests/e2e/arbitrum-mainnet-fork/test_arb_mainnet_core.py, src/tests/e2e/arbitrum-mainnet-fork/test_arb_mainnet_spot.py, src/tests/e2e/arbitrum-mainnet-fork/test_arb_mainnet_synthetix.py, src/tests/e2e/arbitrum-sepolia-fork/conftest.py, src/tests/e2e/arbitrum-sepolia-fork/test_arb_sepolia_core.py, src/tests/e2e/arbitrum-sepolia-fork/test_arb_sepolia_spot.py, src/tests/e2e/arbitrum-sepolia-fork/test_arb_sepolia_synthetix.py, src/tests/e2e/arbitrum-sepolia/conftest.py, src/tests/e2e/base-mainnet-fork/conftest.py
* Adds new argument to the init. This allows users to submit a request timeout for example, which is useful on forks.
* Adds the Arbitrum mainnet deploy
* Improves support for fork tests
=> Add request kwargs

src/setup.py, src/synthetix/perps/perps.py, src/synthetix/spot/constants.py, src/synthetix/spot/spot.py
Set the current timestamp from the fork block timestamp when settling async orders on spot or perps markets.
=> Bug: order settlement on forks

src/synthetix/synthetix.py
Fix a call to `web3.eth.accounts` which sometimes fails on public RPCs. Instead, use the stored RPC signers which is called safely at startup.
=> Bug: Use stored RPC signers

src/setup.py, src/synthetix/contracts/deployments/8453/Pyth.json, src/synthetix/perps/perps.py, src/synthetix/synthetix.py
Adds support for V3 perps deployments which support multicollateral. On initialization, the SDK will check the ABI for multicollateral functions and adjust accordingly.
New functions include:
- `debt` and `collateral_balances` in the `get_margin_info` function
- `pay_debt` in order to pay debt using USD in the connected wallet
- Fix a bug in the `wrap_eth` function when nonces are out of sync
- Add hard-coded Pyth contract for Base mainnet
=> Perps multicollateral support

src/synthetix/perps/constants.py, src/synthetix/perps/perps.py, src/synthetix/pyth/pyth.py, src/synthetix/synthetix.py
Add a `perps_disabled_markets` parameter which allows a user to exclude markets. Additionally, handle an error on the Pyth API when feed ids are missing.
=> Bug: Disabled perps markets

src/setup.py, src/synthetix/contracts/deployments/42161/perpsFactory/PerpsAccountProxy.json, src/synthetix/contracts/deployments/42161/perpsFactory/PerpsMarketProxy.json, src/synthetix/contracts/deployments/42161/spotFactory/SpotMarketProxy.json, src/synthetix/contracts/deployments/42161/system/AccountProxy.json, src/synthetix/contracts/deployments/42161/system/CoreProxy.json, src/synthetix/contracts/deployments/42161/system/USDProxy.json, src/synthetix/contracts/deployments/42161/tBTC.json, src/synthetix/spot/spot.py
- Update hard-coded contracts for the Arbitrum mainnet deployment
- Add the `tBTC` contract as hard-coded
- Adjust the atomic order function to correctly handle slippage
- Additionally, hard-code a catch for USDC on Base, where instead of using an oracle price we specify 1:1 swaps. This change is backwards compatible, however future users can specify `min_amount_received` to override this.
=> Arbitrum Mainnet Updates

src/synthetix/perps/perps.py, src/synthetix/utils/multicall.py, src/tests/test_oracles.py
probably need to add some tests that specifically call `handle_erc7412_error`
=> changes to improve performance of erc7412 required from upstream

src/setup.py, src/synthetix/perps/perps.py, src/synthetix/pyth/pyth.py, src/synthetix/utils/multicall.py
another optimization that was forgotten about in the first pass
please help me test :pray:
=> batch feed_ids to pyth api

src/synthetix/utils/multicall.py
This pull request includes a small change to the `decode_erc7412_oracle_data_required_error` function in the `src/synthetix/utils/multicall.py` file. The change removes print statements used for debugging purposes.
* [`src/synthetix/utils/multicall.py`](diffhunk://#diff-bdc7c8502e12571ec74c8a8e4d8caa2c41ae0132a8139c10a8847d8da9e08c47L47-L49): Removed print statements from the `decode_erc7412_oracle_data_required_error` function.
=> remove excess print statement

src/setup.py, src/synthetix/contracts/contracts.py, src/synthetix/perps/perps.py, src/synthetix/spot/spot.py, src/synthetix/synthetix.py, src/synthetix/utils/multicall.py
Fix the default packaging for the `trusted_multicall_forwarder` contract. It was removed from the `system` folder in recent Cannon packages, therefore `system.oracle_manager.trusted_multicall_forwarder` is a safer way to fetch the contract.
=> Fix default packaging

src/setup.py, src/synthetix/synthetix.py
Fix packaging backward compatibility by supporting both routes:
- `system.trusted_multicall_forwarder`
- `system.oracle_manager.trusted_multicall_forwarder`
=> Fix Packaging
